application: itservzweb
version: 1
runtime: php55
api_version: 1

handlers:

- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /less
  static_dir: less
- url: /vendor
  static_dir: vendor
- url: .*
  script: main.php
